import type { Project, Comment, TechStack } from "@/types/database";

export const TECH_STACKS: TechStack[] = [
  // Frontend
  { id: 1, name: "React", slug: "react", category: "frontend" },
  { id: 2, name: "Next.js", slug: "nextjs", category: "frontend" },
  { id: 3, name: "Vue", slug: "vue", category: "frontend" },
  { id: 4, name: "Svelte", slug: "svelte", category: "frontend" },
  { id: 5, name: "Angular", slug: "angular", category: "frontend" },
  { id: 6, name: "Tailwind CSS", slug: "tailwindcss", category: "frontend" },
  { id: 7, name: "Flutter", slug: "flutter", category: "frontend" },
  { id: 8, name: "React Native", slug: "react-native", category: "frontend" },
  // Backend
  { id: 9, name: "Node.js", slug: "nodejs", category: "backend" },
  { id: 10, name: "Express", slug: "express", category: "backend" },
  { id: 11, name: "FastAPI", slug: "fastapi", category: "backend" },
  { id: 12, name: "Django", slug: "django", category: "backend" },
  { id: 13, name: "Spring Boot", slug: "spring-boot", category: "backend" },
  { id: 14, name: "NestJS", slug: "nestjs", category: "backend" },
  // Database
  { id: 15, name: "PostgreSQL", slug: "postgresql", category: "database" },
  { id: 16, name: "MySQL", slug: "mysql", category: "database" },
  { id: 17, name: "MongoDB", slug: "mongodb", category: "database" },
  { id: 18, name: "Redis", slug: "redis", category: "database" },
  { id: 19, name: "Supabase", slug: "supabase", category: "database" },
  { id: 20, name: "Firebase", slug: "firebase", category: "database" },
  // Language
  { id: 21, name: "TypeScript", slug: "typescript", category: "language" },
  { id: 22, name: "Python", slug: "python", category: "language" },
  { id: 23, name: "Go", slug: "go", category: "language" },
  { id: 24, name: "Rust", slug: "rust", category: "language" },
  { id: 25, name: "Dart", slug: "dart", category: "language" },
  { id: 26, name: "Java", slug: "java", category: "language" },
  { id: 27, name: "Kotlin", slug: "kotlin", category: "language" },
  // Infra
  { id: 28, name: "Docker", slug: "docker", category: "infra" },
  { id: 29, name: "AWS", slug: "aws", category: "infra" },
  { id: 30, name: "Vercel", slug: "vercel", category: "infra" },
  { id: 31, name: "GCP", slug: "gcp", category: "infra" },
  { id: 32, name: "Cloudflare", slug: "cloudflare", category: "infra" },
  // AI
  { id: 33, name: "OpenAI API", slug: "openai-api", category: "ai" },
  { id: 34, name: "LangChain", slug: "langchain", category: "ai" },
  { id: 35, name: "Hugging Face", slug: "huggingface", category: "ai" },
];

const profileA = {
  id: "user-1",
  username: "devkim",
  display_name: "김개발",
  avatar_url: null,
  bio: "풀스택 개발자",
  github_url: null,
  created_at: "2025-01-01T00:00:00Z",
};

const profileB = {
  id: "user-2",
  username: "leecode",
  display_name: "이코드",
  avatar_url: null,
  bio: "프론트엔드 개발자",
  github_url: null,
  created_at: "2025-01-05T00:00:00Z",
};

const profileC = {
  id: "user-3",
  username: "parkmaker",
  display_name: "박메이커",
  avatar_url: null,
  bio: "인디 메이커",
  github_url: null,
  created_at: "2025-02-01T00:00:00Z",
};

export const DUMMY_PROJECTS: Project[] = [
  {
    id: "proj-1",
    user_id: "user-1",
    title: "Dailylog",
    tagline: "개발자를 위한 마이크로 블로깅 — TIL을 30초 안에 기록하고 공유하는 서비스",
    description:
      "Dailylog는 개발자들이 오늘 배운 것(TIL)을 빠르게 기록하고 공유할 수 있는 마이크로 블로깅 플랫폼입니다.\n\n## 주요 기능\n- 마크다운 에디터로 30초 안에 TIL 작성\n- 태그 기반 분류 및 검색\n- 개발자 팔로우 & 피드\n- GitHub 잔디처럼 기록 시각화\n\n## 만들게 된 계기\n매일 배운 것을 기록하고 싶은데, 블로그는 너무 무겁고 트위터는 너무 가벼워서 그 중간 지점의 서비스를 만들었습니다.\n\n## 현재 상태\nMVP 단계로 기본 CRUD와 피드 기능이 구현되어 있습니다. UX 개선과 수익화 모델에 대한 피드백이 필요합니다.",
    demo_url: "https://dailylog.example.com",
    app_store_url: null,
    play_store_url: null,
    github_url: "https://github.com/example/dailylog",
    thumbnail_url: null,
    stage: "mvp",
    feedback_points: ["ux", "business_model"],
    upvote_count: 12,
    comment_count: 5,
    is_published: true,
    created_at: "2025-02-10T09:00:00Z",
    updated_at: "2025-02-15T14:00:00Z",
    profiles: profileA,
    tech_stacks: [
      { id: 2, name: "Next.js", slug: "nextjs", category: "frontend" },
      { id: 19, name: "Supabase", slug: "supabase", category: "database" },
      { id: 21, name: "TypeScript", slug: "typescript", category: "language" },
      { id: 6, name: "Tailwind CSS", slug: "tailwindcss", category: "frontend" },
    ],
  },
  {
    id: "proj-2",
    user_id: "user-2",
    title: "Fontwave",
    tagline: "한글 웹폰트 미리보기 & 비교 도구 — 디자이너와 개발자를 위한 폰트 탐색기",
    description:
      "Fontwave는 한글 웹폰트를 실시간으로 미리보고 비교할 수 있는 도구입니다.\n\n## 주요 기능\n- 100+ 한글 웹폰트 실시간 미리보기\n- 나란히 비교 모드\n- CSS 코드 자동 생성\n- 커스텀 텍스트로 테스트\n\n## 기술적 도전\nGoogle Fonts API를 활용해서 폰트를 동적으로 로딩하는 부분이 가장 까다로웠습니다.",
    demo_url: "https://fontwave.example.com",
    app_store_url: null,
    play_store_url: null,
    github_url: null,
    thumbnail_url: null,
    stage: "launched",
    feedback_points: ["tech_architecture", "feature_suggestion"],
    upvote_count: 24,
    comment_count: 8,
    is_published: true,
    created_at: "2025-01-20T12:00:00Z",
    updated_at: "2025-02-12T09:00:00Z",
    profiles: profileB,
    tech_stacks: [
      { id: 1, name: "React", slug: "react", category: "frontend" },
      { id: 36, name: "Vite", slug: "vite", category: "frontend" },
      { id: 37, name: "Google Fonts API", slug: "google-fonts-api", category: "frontend" },
    ],
  },
  {
    id: "proj-3",
    user_id: "user-3",
    title: "커피챗",
    tagline: "같은 동네 개발자끼리 커피 한잔 — 위치 기반 개발자 네트워킹 앱",
    description:
      "커피챗은 같은 지역의 개발자들을 연결해주는 네트워킹 앱입니다.\n\n## 컨셉\n- 위치 기반으로 근처 개발자 발견\n- 관심 기술 스택 매칭\n- 간편하게 커피챗 요청\n\n## 현재 상태\n아직 아이디어 단계입니다. 비즈니스 모델과 초기 유저 확보 전략에 대한 피드백이 필요합니다.",
    demo_url: null,
    app_store_url: null,
    play_store_url: null,
    github_url: null,
    thumbnail_url: null,
    stage: "idea",
    feedback_points: ["business_model", "marketing"],
    upvote_count: 8,
    comment_count: 11,
    is_published: true,
    created_at: "2025-02-18T15:00:00Z",
    updated_at: "2025-02-18T15:00:00Z",
    profiles: profileC,
    tech_stacks: [
      { id: 7, name: "Flutter", slug: "flutter", category: "frontend" },
      { id: 20, name: "Firebase", slug: "firebase", category: "database" },
      { id: 25, name: "Dart", slug: "dart", category: "language" },
    ],
  },
  {
    id: "proj-4",
    user_id: "user-1",
    title: "Snippy",
    tagline: "코드 스니펫 매니저 — 자주 쓰는 코드를 태그로 정리하고 팀과 공유하는 CLI + 웹 도구",
    description:
      "Snippy는 자주 사용하는 코드 조각을 체계적으로 관리하고 팀과 공유할 수 있는 도구입니다.\n\n## 주요 기능\n- CLI로 터미널에서 바로 스니펫 저장/검색\n- 웹 대시보드에서 태그 기반 관리\n- 팀 워크스페이스 공유\n- VS Code 익스텐션 (개발 중)\n\n## 기술 스택 선택 이유\nSvelte를 웹 프론트엔드로 선택한 이유는 번들 사이즈가 작고 빠르기 때문입니다.",
    demo_url: "https://snippy.example.com",
    app_store_url: null,
    play_store_url: null,
    github_url: "https://github.com/example/snippy",
    thumbnail_url: null,
    stage: "mvp",
    feedback_points: ["tech_architecture", "ux"],
    upvote_count: 17,
    comment_count: 6,
    is_published: true,
    created_at: "2025-02-05T11:00:00Z",
    updated_at: "2025-02-14T16:00:00Z",
    profiles: profileA,
    tech_stacks: [
      { id: 9, name: "Node.js", slug: "nodejs", category: "backend" },
      { id: 15, name: "PostgreSQL", slug: "postgresql", category: "database" },
      { id: 4, name: "Svelte", slug: "svelte", category: "frontend" },
      { id: 28, name: "Docker", slug: "docker", category: "infra" },
    ],
  },
  {
    id: "proj-5",
    user_id: "user-2",
    title: "이력서 AI",
    tagline: "개발자 이력서를 AI가 분석해서 개선점을 알려주는 서비스 — JD 매칭 점수도 제공",
    description:
      "이력서 AI는 개발자 이력서를 업로드하면 AI가 분석해서 개선점을 제안하는 서비스입니다.\n\n## 주요 기능\n- PDF 이력서 업로드 & 파싱\n- AI 기반 이력서 분석 및 개선 제안\n- JD(채용공고) 매칭 점수 산출\n- 섹션별 상세 피드백\n\n## 수익화 고민\n현재 무료로 운영 중인데, 프리미엄 기능을 어떻게 설계할지 고민입니다.",
    demo_url: "https://resume-ai.example.com",
    app_store_url: null,
    play_store_url: null,
    github_url: null,
    thumbnail_url: null,
    stage: "growing",
    feedback_points: ["business_model", "marketing"],
    upvote_count: 31,
    comment_count: 14,
    is_published: true,
    created_at: "2025-01-10T08:00:00Z",
    updated_at: "2025-02-20T10:00:00Z",
    profiles: profileB,
    tech_stacks: [
      { id: 22, name: "Python", slug: "python", category: "language" },
      { id: 11, name: "FastAPI", slug: "fastapi", category: "backend" },
      { id: 33, name: "OpenAI API", slug: "openai-api", category: "ai" },
      { id: 2, name: "Next.js", slug: "nextjs", category: "frontend" },
    ],
  },
  {
    id: "proj-6",
    user_id: "user-3",
    title: "DevPulse",
    tagline: "개발 팀의 건강 상태를 체크하는 익명 설문 도구 — 번아웃 지표를 시각화",
    description:
      "DevPulse는 개발 팀의 건강 상태를 정기적으로 체크하는 익명 설문 도구입니다.\n\n## 주요 기능\n- 주간/격주 자동 설문 발송\n- 익명 응답으로 솔직한 피드백\n- 번아웃 지표 시각화 (Chart.js)\n- 팀 트렌드 분석 대시보드\n\n## 타겟\nCTO, 테크 리드, 엔지니어링 매니저를 주요 타겟으로 합니다.",
    demo_url: "https://devpulse.example.com",
    app_store_url: null,
    play_store_url: null,
    github_url: null,
    thumbnail_url: null,
    stage: "mvp",
    feedback_points: ["ux", "feature_suggestion"],
    upvote_count: 9,
    comment_count: 3,
    is_published: true,
    created_at: "2025-02-22T13:00:00Z",
    updated_at: "2025-02-22T13:00:00Z",
    profiles: profileC,
    tech_stacks: [
      { id: 3, name: "Vue", slug: "vue", category: "frontend" },
      { id: 19, name: "Supabase", slug: "supabase", category: "database" },
      { id: 38, name: "Chart.js", slug: "chartjs", category: "frontend" },
      { id: 30, name: "Vercel", slug: "vercel", category: "infra" },
    ],
  },
];

export const DUMMY_COMMENTS: Comment[] = [
  {
    id: "comment-1",
    project_id: "proj-1",
    user_id: "user-2",
    parent_id: null,
    body: "TIL 기록 시각화가 GitHub 잔디처럼 되면 정말 좋을 것 같아요. 매일 기록하는 동기부여가 될 수 있겠네요!",
    feedback_point: "ux",
    created_at: "2025-02-11T10:00:00Z",
    updated_at: "2025-02-11T10:00:00Z",
    profiles: profileB,
  },
  {
    id: "comment-2",
    project_id: "proj-1",
    user_id: "user-3",
    parent_id: null,
    body: "수익화 모델로는 프리미엄 테마나 통계 기능을 유료화하는 것은 어떨까요? 기본 기록 기능은 무료로 두고요.",
    feedback_point: "business_model",
    created_at: "2025-02-12T14:30:00Z",
    updated_at: "2025-02-12T14:30:00Z",
    profiles: profileC,
  },
  {
    id: "comment-3",
    project_id: "proj-1",
    user_id: "user-2",
    parent_id: "comment-2",
    body: "동의합니다. 팀 기능을 만들어서 B2B로 가는 것도 고려해볼 만 할 것 같아요.",
    feedback_point: null,
    created_at: "2025-02-12T15:00:00Z",
    updated_at: "2025-02-12T15:00:00Z",
    profiles: profileB,
  },
  {
    id: "comment-4",
    project_id: "proj-1",
    user_id: "user-3",
    parent_id: null,
    body: "에디터에서 코드 블록 지원이 되면 개발자 TIL에 딱일 것 같습니다. 마크다운 문법 하이라이팅도 있으면 좋겠어요.",
    feedback_point: "ux",
    created_at: "2025-02-13T09:00:00Z",
    updated_at: "2025-02-13T09:00:00Z",
    profiles: profileC,
  },
  {
    id: "comment-5",
    project_id: "proj-1",
    user_id: "user-1",
    parent_id: "comment-4",
    body: "감사합니다! 코드 블록은 다음 업데이트에서 추가할 예정이에요 🙏",
    feedback_point: null,
    created_at: "2025-02-13T10:00:00Z",
    updated_at: "2025-02-13T10:00:00Z",
    profiles: profileA,
  },
];
